{
 "title": "vearch向量库监控",
 "tags": [ "vearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": "Vearch_request_duration_seconds_count"
   }
  ]
 },
 "panels": [
  {
   "title": "Bulk Search Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\",key='handleBulkSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulkSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\",key='handleBulkSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulkSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\",key='handleBulkSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulkSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp50"
    }
   ]
  },
  {
   "title": "Bulk Search Requests (minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulkSearchDoc'}[59s])) by (key)",
     "legendFormat": "search"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\",key='handleSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\",key='handleSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\",key='handleSearchDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleSearchDoc'}[59s])) by (key)",
     "legendFormat": "tp50"
    }
   ]
  },
  {
   "title": "Search Requests (minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleSearchDoc'}[1m])) by (key)",
     "legendFormat": "search/m"
    },
    {
     "expr": "sum(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleSearchDoc'}) ",
     "legendFormat": "search/s"
    }
   ]
  },
  {
   "title": "handlerQueryDocByIds Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\",key='handlerQueryDocByIds'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handlerQueryDocByIds'}[59s])) by (key)",
     "legendFormat": "tp99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\",key='handlerQueryDocByIds'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handlerQueryDocByIds'}[59s])) by (key)",
     "legendFormat": "tp90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\",key='handlerQueryDocByIds'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handlerQueryDocByIds'}[59s])) by (key)",
     "legendFormat": "tp50"
    }
   ]
  },
  {
   "title": "handlerQueryDocByIds (minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handlerQueryDocByIds'}[59s])) by (key)",
     "legendFormat": "handlerQueryDocByIds"
    }
   ]
  },
  {
   "title": "Add Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\",key='handleUpdateDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleUpdateDoc'}[59s])) by (key)",
     "legendFormat": "tp99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\",key='handleUpdateDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleUpdateDoc'}[59s])) by (key)",
     "legendFormat": "tp90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\",key='handleUpdateDoc'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleUpdateDoc'}[59s])) by (key)",
     "legendFormat": "tp50"
    }
   ]
  },
  {
   "title": "Add Requests (minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleUpdateDoc'}[59s])) by (key)",
     "legendFormat": "add"
    }
   ]
  },
  {
   "title": "handleBulk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\",key='handleBulk'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulk'}[59s])) by (key)",
     "legendFormat": "tp99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\",key='handleBulk'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulk'}[59s])) by (key)",
     "legendFormat": "tp90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\",key='handleBulk'}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulk'}[59s])) by (key)",
     "legendFormat": "tp50"
    }
   ]
  },
  {
   "title": "handleBulk Requests (minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key='handleBulk'}[59s])) by (key)",
     "legendFormat": "handleBulk"
    }
   ]
  },
  {
   "title": "DB数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbInfo{job=\"$cluster\",metric=\"DBNum\"}",
     "legendFormat": "DBNum"
    }
   ]
  },
  {
   "title": "单库文档量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dbInfo{job=\"$cluster\",metric=\"docNum\"}) by (tag1)",
     "legendFormat": "{{tag1}}"
    }
   ]
  },
  {
   "title": "space_num数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbInfo{job=\"$cluster\",metric=\"SpaceNum\"}"
    }
   ]
  },
  {
   "title": "PS节点数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbInfo{job=\"$cluster\",metric=\"ServerNum\"}",
     "legendFormat": "节点数"
    }
   ]
  },
  {
   "title": "leader_信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbInfo{job=\"$cluster\",metric=\"leaderNum\"}",
     "legendFormat": "{{tag1}}"
    }
   ]
  },
  {
   "title": "partitionNum数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbInfo{job=\"$cluster\",metric=\"partitionNum\"} "
    }
   ]
  },
  {
   "title": "机器文档数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dbInfo{job=\"$cluster\",metric=\"PartitionDoc\"}) by (tag1,tag2)",
     "legendFormat": "{{tag1}}_{{tag2}}"
    }
   ]
  },
  {
   "title": "机器磁盘占用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dbInfo{job=\"$cluster\",metric=\"PartitionSize\"}) by (tag2,tag1)",
     "legendFormat": "{{tag1}}_{{tag2}}"
    }
   ]
  },
  {
   "title": "总调用次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key!='nil'}[59s]))",
     "legendFormat": "总调用次数"
    }
   ]
  },
  {
   "title": "总体性能指标",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.999\"}[59s]))/sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s]))",
     "legendFormat": "TP999"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\"}[59s]))/sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s]))",
     "legendFormat": "TP99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.95\"}[59s]))/sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s]))",
     "legendFormat": "TP95"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.90\"}[59s]))/sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s]))",
     "legendFormat": "TP90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.5\"}[59s]))/sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s]))",
     "legendFormat": "TP50"
    }
   ]
  },
  {
   "title": "方法调用次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\",key!='nil'}[59s])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "方法性能指标",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.9\"}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s])) by (key)",
     "legendFormat": "{{key}}_TP90"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.99\"}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s])) by (key)",
     "legendFormat": "{{key}}_TP99"
    },
    {
     "expr": "sum(sum_over_time(Vearch_request_duration_seconds{job=\"$cluster\",quantile=\"0.95\"}[59s])) by (key) /sum(sum_over_time(Vearch_request_duration_seconds_count{job=\"$cluster\"}[59s])) by (key)",
     "legendFormat": "{{key}}_TP95"
    }
   ]
  }
 ]
}